-- MySQL Script generated by MySQL Workbench
-- Fri Jul 18 13:28:34 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema greenBelt2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `greenBelt2` ;
CREATE SCHEMA IF NOT EXISTS `greenBelt2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `greenBelt2` ;

-- -----------------------------------------------------
-- Table `greenBelt2`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greenBelt2`.`users` ;

CREATE TABLE IF NOT EXISTS `greenBelt2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenBelt2`.`incidents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greenBelt2`.`incidents` ;

CREATE TABLE IF NOT EXISTS `greenBelt2`.`incidents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_incidents_users1_idx` (`author_id` ASC),
  CONSTRAINT `fk_incidents_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `greenBelt2`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenBelt2`.`user_witnessed_incident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greenBelt2`.`user_witnessed_incident` ;

CREATE TABLE IF NOT EXISTS `greenBelt2`.`user_witnessed_incident` (
  `user_id` INT NOT NULL,
  `incident_id` INT NOT NULL,
  INDEX `fk_user_witnessed_incident_users_idx` (`user_id` ASC),
  INDEX `fk_user_witnessed_incident_incidents1_idx` (`incident_id` ASC),
  CONSTRAINT `fk_user_witnessed_incident_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `greenBelt2`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_witnessed_incident_incidents1`
    FOREIGN KEY (`incident_id`)
    REFERENCES `greenBelt2`.`incidents` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
